---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sapnyrqx/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R lib $DEPLOYPATH
    - /bin/cp -R mail $DEPLOYPATH
    - /bin/cp -R project-docs $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH